packages:
  - "apps/*"
  - "packages/*"
  - "plugins/*/*"
  - "devtools/*"
  - "vscode-extension"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  keytar: true
  msgpackr-extract: true
  prisma: true
