apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: astramind-gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  encrypted: "true"
  kmsKeyId: "arn:aws:kms:region:account:key/astramind-storage-key"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
