apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: astramind-staging-ingress
  namespace: astramind
spec:
  rules:
    - host: "staging.astramind.ai"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 4000
