apiVersion: apps/v1
kind: Deployment
metadata:
  name: astramind-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: astramind-frontend
  template:
    metadata:
      labels:
        app: astramind-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}"
          ports:
            - containerPort: 3000
