apiVersion: apps/v1
kind: Deployment
metadata:
  name: astramind-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: astramind-backend
  template:
    metadata:
      labels:
        app: astramind-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          ports:
            - containerPort: 4000
