apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: astramind-ingress
spec:
  rules:
    - host: "api.astramind.ai"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: astramind-backend
                port:
                  number: 4000
